import Subcubic.Basic
import Subcubic.ColoringLemmas
import Subcubic.MatchingCut
import Subcubic.Pattern
import Subcubic.TailReducers
import Subcubic.CutEnhancers
import Subcubic.Lemma3_3
import Subcubic.Lemma3_5
import Subcubic.Lemma4_2
import Subcubic.Lemma4_3
import Subcubic.Lemma4_4
import Subcubic.Lemma4_5
import Subcubic.Lemma4_7
import Subcubic.Lemma4_8
import Subcubic.Lemma4_10
import Subcubic.Lemma4_12
import Subcubic.Lemma2_7
import Subcubic.Lemma5_2
import Subcubic.Lemma5_3
import Subcubic.Lemma5_4
import Subcubic.Lemma5_5
import Subcubic.Lemma5_6
import Subcubic.Lemma5_7
